# Generated by Django 4.2.16 on 2024-09-25 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sysuser",
            old_name="avater",
            new_name="avatar",
        ),
    ]
